baseURL = 'https://satoing.github.io'
languageCode = 'en-us'
title = 'Jup的博客'
theme = "paper"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "分类"
    url = "/categories"
    weight = 3
  [[menu.main]]
    name = "标签"
    url = "/tags"
    weight = 4
    [[menu.main]]
    name = "关于"
    url = "/about"
    weight = 5

[outputs]
  home = ["HTML", "JSON"]  # 允许生成JSON

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'satoing'                 # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = 'https://image.lulukiko.top:7326/yuque/0/2025/png/2648742/1746202337716-avatar/7a5519fa-173b-4d39-ac28-a1c6894a08f2.png?x-oss-process=image%2Fresize%2Cm_fill%2Cw_72%2Ch_72%2Fformat%2Cpng'                 # gravatar email or image url
  name = 'jup'
  bio = '青山旧歌谣'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = false                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "https://image.lulukiko.top:7326/yuque/0/2025/png/2648742/1746202337716-avatar/7a5519fa-173b-4d39-ac28-a1c6894a08f2.png?x-oss-process=image%2Fresize%2Cm_fill%2Cw_48%2Ch_48%2Fformat%2Cpng"                   # customize the default favicon
  appleTouchIcon = "https://image.lulukiko.top:7326/yuque/0/2025/png/2648742/1746202337716-avatar/7a5519fa-173b-4d39-ac28-a1c6894a08f2.png?x-oss-process=image%2Fresize%2Cm_fill%2Cw_48%2Ch_48%2Fformat%2Cpng"   # customize the default Apple touch icon

